const FETCH_ANNOUNCMENTS_BEGIN = 'FETCH_ANNOUNCMENTS_BEGIN';
const SET_ANNOUNCMENTS = 'SET_ANNOUNCMENTS';
const ADD_ANNOUNCMENT = 'ADD_ANNOUNCMENT';

export default {
  FETCH_ANNOUNCMENTS_BEGIN,
  SET_ANNOUNCMENTS,
  ADD_ANNOUNCMENT,
};
