const FETCH_ANNOUNCMENTS_BEGIN = 'FETCH_ANNOUNCMENTS_BEGIN';
const FETCH_ANNOUNCMENTS_SUCCESS = 'FETCH_ANNOUNCMENTS_SUCCESS';
const FETCH_ANNOUNCMENTS_ERROR = 'FETCH_ANNOUNCMENTS_ERROR';
const SET_ANNOUNCMENTS = 'SET_ANNOUNCMENTS';
const ADD_ANNOUNCMENT = 'ADD_ANNOUNCMENT';

export default {
  FETCH_ANNOUNCMENTS_BEGIN,
  FETCH_ANNOUNCMENTS_SUCCESS,
  FETCH_ANNOUNCMENTS_ERROR,
  SET_ANNOUNCMENTS,
  ADD_ANNOUNCMENT,
};
