const FETCH_QUIZZES_BEGIN = 'FETCH_QUIZZES_BEGIN';
const FETCH_QUIZZES_SUCCESS = 'FETCH_QUIZZES_SUCCESS';
const FETCH_QUIZZES_ERROR = 'FETCH_QUIZZES_ERROR';
const SET_QUIZZES = 'SET_QUIZZES';
const ADD_QUIZ = 'ADD_QUIZ';

export default {
  FETCH_QUIZZES_BEGIN,
  FETCH_QUIZZES_SUCCESS,
  FETCH_QUIZZES_ERROR,
  SET_QUIZZES,
  ADD_QUIZ,
};
